# Site settings
title: Share a Bit
email: s4sarath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog, where I scribble about my thoughts , feelings and knowledge .
  "As the heat of fire reduces wood to ashes, the fire of knowledge burns to ashes all karma - Krishna"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://s4sarath.github.io" # yourdomain.com # the base hostname & protocol for your site
twitter_username: (Never!)
github_username: s4sarath
comments: true
# Build settings
markdown: kramdown
mathjax: true
#markdown: redcarpet # Does not make multiline ``` ... ``` work!
gems: [jekyll-paginate]

paginate: 20
#excerpt_separator: <!--more--> # Has problems with hyperlinks in the excerpt
